### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by lmjst** [Dammmien/brackets-unused-files#4]
Brackets says there is an error

**Comment by ManvendraSK** [comment]
@lmjst @Dammmien 

I have fixed this issue and is available in this PR https://github.com/Dammmien/brackets-unused-files/pull/5. 

As soon as this PR gets merge you can reinstall this extension and it should work.

**Comment by ManvendraSK** [comment]
@Dammmien Please approve this PR, and we will be able to close this issue after the verification.

**Comment by ManvendraSK** [comment]
It is resolved. https://github.com/Dammmien/brackets-unused-files/pull/5
